language: node_js
node_js: node
addons:
  firefox: '49.0'
install:
- npm install
- npm run install:http
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- npm run build:foglet
- ls -R ./build ./src
- npm test
- npm run cover
deploy:
  provider: npm
  email: folkvir@outlook.fr
  api_key:
    secure: TY3Y9fcDdD/ltb22pB41aT8OX/qt9Q1NyGv+wYkjitIcDhqrAr4a4RETXZOYY09Kp/LqKMqrgfgsYjHK8v1dSQpxmfxf9JGuR7Q08SJ6UTdQLgAsafS/WoIZsbjGq825RfNaoao9w1qVW/x2fEi4PffXzzRFr7JrI6pfKFKwf6J8xVXUSV3oGBi4kZ2L9t2iygs5gePwEHU+2+/2Hi3a8rnnNObpszpWN+mmMAj952IwZtG0goBZnqLrLeH9Ute/dlBrea1eQHkQhfz+XYwYzsW8DEGKIaWjnucuOrIhOQyq9ZNArQ1QP2a8zN/nUpeHGDNrKF9BQ92BuL/jMSj386XeSwcRuPdbr+Fa0aG/iZH5p/iSknEdXP9bbik99hVrvwZJ1AzM0zs7MUCzMpe4vPLNE83u5nMsrajhNtdsSvHYJb1ltOYUGpdsgGAzu/KETVwh6Ffd3NnStMBHw1hgUVih3rSm4iVo7de85yhySr/j8GDHF3u3GxeAN6YnRvcA9iA9jHjSQetMp6TW2v3zh4bTxHkICx8w1q3Bv+qjfEig4fNYLcsNTNiU1ZmIfVnCLV99DG+fEvZtNcXMLW0XkEDcRtuXjf03yQYjUs50QlUDDdFHB/lVSWVn73TghY7FjdsLlAoIvI8iFufz4y2Zb9mHZduBM3RhlYOsFB3P3fQ=
  on:
    tags: true
    repo: folkvir/foglet-core
